Filter
daemabnb/Daema-BnB-web pull request #10
Opened 2019-05-29 01:26 UTC by khg0712

2019-05-29 02:17 UTC, engolder requested changes

2019-05-29 02:17 UTC, engolder commented on src/presentations/DateFilter/index.tsx
> +      <S.Dropdownbtn isSelected={isSelected}>{value}</S.Dropdownbtn>
`DropdownBtn`은 `DateFilter`와 `TypeFilter`에서 중복으로 사용됨으로 공통컴포넌트로 빼는 것이 좋을 것 같습니다

2019-05-29 02:17 UTC, engolder commented on src/presentations/DateFilter/index.tsx
> +      <S.Dropdownbtn isSelected={isSelected}>{value}</S.Dropdownbtn>
`DropdownButton`으로 재명칭하는게 좋을 것 같습니다.
먼저 짧게 줄인 형태인 `btn`보다 이미 `Button`이라는 컴포넌트가 있기 때문에 일관된 명칭으 사용하는 편이 좋을 것 같고,
cabelCase를 사용하는 것이 좋을 것 같습니다

2019-05-29 02:17 UTC, engolder commented on src/presentations/DateFilter/styles.ts
> +    border-color: ${({ isSelected }: DropdownbtnProps) =>
함수를 다섯번 사용하는 것 보다는
```ts
${({ isSelected }: DropdownbtnProps) => {
  return css`border-color: ${isSelected ? '#008489' : '#dce0e0'}
    ...
    `
}
```
형태가 가독성에 좋습니다

2019-05-29 02:17 UTC, engolder commented on src/presentations/FilterDropdown/index.ts
> +  ${({ isActive }: FilterDropdownProps) => !isActive && 'display: none;'}
`'display: none;'`과 같은 하드코딩보다는
```css`display: none;` ```과 같이 api를 사용하려 해주세요!

2019-05-29 02:17 UTC, engolder commented on src/presentations/TypeFilter/index.tsx
> +  contentItems: string[];
`contentItems: Array<string>`과 같이 작성할 수도 있습니다! (참고)

2019-05-29 02:17 UTC, engolder commented on src/presentations/TypeFilter/index.tsx
> +  onToggleFilter: (value: boolean) => void;
value보다는 isActive나 status같은 명칭이 나을것같네요

2019-05-29 02:17 UTC, engolder commented on src/presentations/TypeFilter/index.tsx
> +  const isSelected = value !== '타입';
`'타입'`과 같은 리터럴문자열은 오류발생시 추적이어렵습니다.
차라리 default값을 주지말고 value가 undefined인지 아닌지로 selected여부를 판단하는게 좋을 것 같네요

2019-05-29 02:17 UTC, engolder commented on src/presentations/TypeFilter/index.tsx
> +  const dropdownItems = contentItems.map((content, i) => (
index 인자를 `i`라고 명칭하는 것은 문제가 없지만, 코드간 통일성은 맞춰야할 필요성이 생길 수 있습니다. index변수를 사용하는 상황은 처음이라 수정하실 필요는 없습니다.

2019-05-29 02:17 UTC, engolder commented on src/presentations/TypeFilter/index.tsx
> +    <S.DropdownItem key={i} onClick={onSelectType.bind(null, content)}>
단순히 index를 list item에 할당하면 콘솔 에러는 피할 수 있지만, 리액트의 리스트렌더링에 성능적 이점을 놓치게됩니다. 차라리 dropdownItem에 id속성을 만들고 할당하는 편이 좋아보입니다.

2019-05-29 02:17 UTC, engolder commented on src/presentations/TypeFilter/index.tsx
> +  contentItems: string[];
`contentItems`보다는 `dropdownItems`가 더 명확한 이름같습니다.

2019-05-29 02:17 UTC, engolder commented on src/presentations/TypeFilter/index.tsx
> +    <S.DropdownItem key={i} onClick={onSelectType.bind(null, content)}>
bind에서 첫번째인자로서 undefined대신 null을 사용하신대에는 이유가있나요? 궁금합니다.

2019-05-29 02:17 UTC, engolder commented on src/presentations/TypeFilter/index.tsx
> +  onToggleFilter: (value: boolean) => void;
`onToggleFilter`만 보았을때는 무엇을 toggle한다는 것인지 파악하기 힘듭니다.
`onToggleFilterDropdown`과 같이 더 명시적인 네이밍은 어떨까요?

2019-05-29 02:19 UTC, khg0712 commented on src/presentations/DateFilter/index.tsx
> +      <S.Dropdownbtn isSelected={isSelected}>{value}</S.Dropdownbtn>
넵

2019-05-29 02:23 UTC, khg0712 commented on src/presentations/TypeFilter/index.tsx
> +  const isSelected = value !== '타입';
사실 그렇게 짜려고 했는데 머리에서 에러가 났네용

2019-05-31 05:52 UTC, engolder approved these changes

2019-05-31 06:02 UTC, merged