Image pagination
daemabnb/Daema-BnB-web pull request #11
Opened 2019-05-29 02:54 UTC by khg0712

2019-05-31 05:47 UTC, engolder requested changes

2019-05-31 05:47 UTC, engolder commented on src/presentations/ImagePagination/index.tsx
> +  onChange: (next: number) => void;
selectedIndex와 onChange를 조상에서 관리해줘야할 이유가 있을까요? 부모입장에서 image pagination컴포넌트에게 image url들을 내려주고 알아서 보여주길 바라지, 유저가 현재 몇번째 이미지를 보고있는지를 직접 관여해야할 책임은 없어보입니다.

2019-05-31 05:47 UTC, engolder commented on src/presentations/ImagePagination/index.tsx
> +};
순수함수는 utils로 빼면 좋을 것 같네요.

2019-05-31 05:47 UTC, engolder commented on src/presentations/ImagePagination/styles.ts
> +  height: ${(props: PaginationItemProps) => (props.isSelected ? '8px' : '6px')};
가독성을 위해
```
${(props: PaginationItemProps) => css`
   ...
`}
```
형태로 사용해줍시다.

2019-05-31 05:47 UTC, engolder commented on src/presentations/ImagePagination/index.tsx
> +    </S.ImagePagination>
`ImagePagination`과 `Pagination`의 네이밍이 매우 햇갈립니다. 차라리 컴포넌트의 이름을
ImagePresenter로 바꾸는건 어떨까요?
생각을해보면 부모입장에서 이 컴포넌트에게 이미지들을 props로 내려주고, 유저에게 보여주면 된다고 생각할 것이지, 이 컴포넌트가 유저에게 이미지를 어떤방법(페이징)으로 보여주던지는 관심이 없을 것 같다는 의견입니다.

2019-05-31 05:47 UTC, engolder commented on src/presentations/ImagePagination/styles.ts
> +export const PaginationItem = styled.div`
`paginationDot`이나 `paginationLink`같은건 어떨까요 `paginationItem`자체로는 무엇을 뜻하는지 짐작하기 어렵습니다.

2019-05-31 05:47 UTC, engolder commented on src/presentations/ImagePagination/styles.ts
> +  isSelected: boolean;
`isSelected`보다는 페이지 개념이니까 `isCurrent`가 어떨까요?

2019-05-31 05:47 UTC, engolder commented on src/presentations/ImagePagination/index.tsx
> +type Direction = 1 | -1;
1과 -1중 어느쪽이 오른쪽, 왼쪽인지 파악하기 힘듭니다.
union type이나 enum을 사용하죠!
`Direction = 'left' | 'right'`

2019-05-31 07:33 UTC, khg0712 commented on src/presentations/ImagePagination/styles.ts
> +export const PaginationItem = styled.div`
PageIndicatorDot로 수정!

2019-05-31 07:35 UTC, khg0712 commented on src/presentations/ImagePagination/styles.ts
> +  isSelected: boolean;
현재 페이지로 선택되었다는 의미로 볼 수 있으니까 괜찮아 보이는데 어떠신가요?

2019-05-31 07:54 UTC, khg0712 commented on src/presentations/ImagePagination/index.tsx
> +type Direction = 1 | -1;
그 방식이 조금 더 명시적인 것 같네요!

2019-05-31 08:15 UTC, khg0712 commented on src/presentations/ImagePagination/index.tsx
> +    </S.ImagePagination>
[Carousel](https://getbootstrap.com/docs/4.3/components/carousel/)이 저런 컴포넌트를 지칭하는 말이더라구요 그래서 변수 네이밍을 대폭 변경했습니다.

2019-06-02 04:21 UTC, engolder approved these changes
늦게봐서 죄송합니다. 코드 아주 맘에드네용 :+1:

2019-06-02 09:54 UTC, merged