Login
daemabnb/Daema-BnB-web pull request #15
Opened 2019-06-13 01:25 UTC by khg0712

2019-06-13 11:13 UTC, engolder requested changes

2019-06-13 11:13 UTC, engolder commented on src/lib/user.ts
> +const baseUrl = 'https://52.79.121.254/user';
url파일을 따로 만들죠 다른 매퍼에서도 쓸 수 있기때문에

2019-06-13 11:13 UTC, engolder commented on src/lib/user.ts
> +  axios.post(
axios<responseType>.post() 형태로 사용하면 response에 타입을 지정해줄 수 있습니다

2019-06-13 11:13 UTC, engolder commented on src/pages/Signin/index.tsx
> +
의미없는 공백은 지워주세요 :+1:

2019-06-13 11:13 UTC, engolder commented on src/pages/Signin/index.tsx
> +        appId="856575621215696"
apy key는 소스코드에 노출시키면 안됩니다!!
환경번수를 통해 가져오도록합시다

2019-06-13 11:13 UTC, engolder commented on src/pages/Signin/index.tsx
> +    try {
error가 발생할 소지가 없어보입니다

2019-06-13 11:13 UTC, engolder commented on src/pages/Signup.tsx
> +  const [emailSended, setEmailSended] = useState(false);
boolean값이니까 is prefix를 붙이는게 어떨까요?? (의견)

2019-06-13 11:13 UTC, engolder commented on src/pages/Signup.tsx
> +  const checkToken = () => {
크게 상관은 없지만 퍼포먼스면에서 useCallback을 사용해보도록합시다

2019-06-13 11:13 UTC, engolder commented on src/pages/Signup.tsx
> +          console.log(e);
예외처리를 해야할 것 같습니다. 그리고 로깅 코드는 제외해줍시다

2019-06-13 11:13 UTC, engolder commented on src/pages/Signup.tsx
> +          history.push('/');
response를 확인한 후 pushing을 해 주어야할 것 같습니다

2019-06-13 11:13 UTC, engolder commented on src/pages/Signup.tsx
> +    checkToken();
checkToken함수 호출의 위치가 잘못된것 같습니다 if문 전으로 이동시켜주세요

2019-06-13 11:13 UTC, engolder commented on src/pages/Signup.tsx
> +          setEmailSended(true);
response를 확인한 후 분기해주어야할 것 같습니다

2019-06-13 11:13 UTC, engolder commented on src/presentations/LabeledTextInput/index.tsx
> +    const Label = label && <S.Label>{label}</S.Label>;
변수이름은 camelCase를 사용해주세요

2019-06-13 11:13 UTC, engolder commented on src/utils/deleteCookie.ts
> +export const deleteCookie = (name: string) => {
cookie는 외부저장소로 볼 수 있기때문에 utils보다는 apis나 lib같은 이름의 디렉토리에 위치하는 것이 맞다고생각합니다.

2019-06-13 11:13 UTC, engolder commented on src/utils/deleteCookie.ts
> +  document.cookie = `${name}=; expires=${date.toUTCString()}; path=/`;
localStorage대신 cookie를 사용하는 이유가있나요?
제가 알기로는 cookie의 대체 방안으로 localStorage와 sessionStorage가 새롭게 추가된 것으로 알고있습니다
cookie보안 이슈가 몇개있었고(기억은 안나지만) 목적이 clientStorage보단 server side session connection용도로 쓰였던 것 같습니다.

2019-06-13 11:17 UTC, engolder commented
Redux store에 token을 저장해야할 필요성이 있어보입니다. 그리고 생각해보니 localStorage와 같은 외부저장소에 데이터를 저장하고 가져오는 역할을 하는 부분은 redux코드부분에서 해야할 것 같네요.

2019-06-13 14:13 UTC, khg0712 commented on src/lib/user.ts
> +const baseUrl = 'https://52.79.121.254/user';
`axios.create` 라는 좋은 함수가 있네요 이걸로 돌려쓰면 될 것 같아요

2019-06-13 14:23 UTC, khg0712 commented on src/lib/user.ts
> +  axios.post(
response가 없는 api엔 지정하지 않아도 되겠네요

2019-06-13 14:55 UTC, khg0712 commented on src/pages/Signup.tsx
> +  const [emailSended, setEmailSended] = useState(false);
ㅜㅜ 저는 안붙일래요

2019-06-13 14:55 UTC, khg0712 commented on src/pages/Signup.tsx
> +          console.log(e);
상태코드에 따른 처리를 하라는 말씀이시죠?

2019-06-13 14:59 UTC, khg0712 commented on src/pages/Signup.tsx
> +          console.log(e);
네트워크 상에 에러가 발생했을 때는 어떻게 처리해야 할까요?

2019-06-13 15:02 UTC, khg0712 commented on src/utils/deleteCookie.ts
> +export const deleteCookie = (name: string) => {
sessionStorage로 바꿨습니당

2019-06-13 15:02 UTC, khg0712 commented on src/utils/deleteCookie.ts
> +  document.cookie = `${name}=; expires=${date.toUTCString()}; path=/`;
세션 스토리지 사용!

2019-06-25 07:59 UTC, khg0712 commented on src/pages/Signup.tsx
> +  const checkToken = () => {
다음부터 쓰겠습니당

2019-06-25 23:48 UTC, engolder commented on src/lib/user.ts
> +  axios.post(
response가 없는 api엔 없다고 지정을 해주어야죠! 아니면 any값이 들어갑니다

2019-06-26 00:00 UTC, engolder requested changes

2019-06-26 00:00 UTC, engolder commented on src/lib/sessionStorage.ts
> +export const getSessionStorage = (name: string) => sessionStorage.getItem(name);
이렇게사용하게되면 해당 어떤 key에 어떤 value가 들어가는지 근본적인 문제는 해결할수없습니다. 그냥 sessionStorage를 사용하는 것이랑 같은 것이죠, 아래처럼 어떤 코드에서 불러오더라도 리턴값이 명확한 함수를 사용합시다. api코드를 따로 분리하고자 하는 이유는 문자열 리터럴에대한 오류를 방지하기 위함입니다.
```ts
getToken = (): string? => {
  sessionStorage.getItem('token')
}
```

2019-06-26 00:00 UTC, engolder commented on src/lib/user.ts
> +  );
response의 return값이 비어있다면 이 또한 명시를 해주는 편이 좋아보입니다!

2019-06-26 00:00 UTC, engolder commented on src/pages/Signup.tsx
> +      signup(email, validation, token)
외부 세계와의 통신을 하는 코드는 view로직에서 분리하는게 유지보수면에서 좋아보입니다. redux같은 라이브러리를사용해서 비지니스로직과 presentation로직을 분리합시다.

2019-06-26 00:03 UTC, khg0712 commented on src/lib/sessionStorage.ts
> +export const getSessionStorage = (name: string) => sessionStorage.getItem(name);
아 거기까진 생각못했네요

2019-06-26 00:03 UTC, khg0712 commented on src/lib/user.ts
> +  );
넵

2019-06-26 01:21 UTC, khg0712 commented on src/pages/Signup.tsx
> +      signup(email, validation, token)
리덕스 작업을 register 브랜치에서 작업해서 분리는 여기서 당장 못할 것 같습니다.

2019-06-26 01:26 UTC, merged