Card
daemabnb/Daema-BnB-web pull request #2
Opened 2019-05-21 01:12 UTC by khg0712

2019-05-21 12:26 UTC, engolder requested changes

2019-05-21 12:26 UTC, engolder commented on src/presentations/Card/index.tsx
> +} from './styles';
CardConatiner는 적절하지 못한 네이밍같습니다 presentational components와 container components로 컴포넌트를 구분하자는 방법을 사용한 시점에서 container의 의미가 혼용될 수 있을 것 같습니다. import * as S로 네임스페이스를 줘서 Card로 사용합시다

2019-05-21 12:26 UTC, engolder commented on src/presentations/Card/index.tsx
> +import { formatDate } from '../../utils/formatDate';
index.ts를 통해 가져오는게 어떨까요

2019-05-21 12:26 UTC, engolder commented on src/presentations/Card/index.tsx
> +          ) : null}
jsx코드 에서 multiline 표현식을 포함하는 것은 가독성을 떨어뜨립니다. 변수로 분리해주세요!

2019-05-21 12:26 UTC, engolder commented on src/presentations/Card/index.tsx
> +          ) : null}
startDate에 따라서 보여줄지 말지 여부를 결정하는 것이라면
간결하게 javascript and 연산자를 사용하는 것이 가독성에 좋습니다
startDate && <JSX />

2019-05-21 12:27 UTC, engolder approved these changes

2019-05-21 12:27 UTC, engolder commented on src/presentations/Card/index.tsx
> +interface Props {
CardProps로 바꾸고 export 해주세요

2019-05-24 06:03 UTC, khg0712 commented on src/presentations/Card/index.tsx
> +} from './styles';
넵!

2019-05-24 06:32 UTC, khg0712 commented on src/presentations/Card/index.tsx
> +import { formatDate } from '../../utils/formatDate';
넵!

2019-05-24 07:09 UTC, khg0712 commented on src/presentations/Card/index.tsx
> +          ) : null}
넵!

2019-05-24 10:15 UTC, khg0712 commented on src/presentations/Card/index.tsx
> +interface Props {
외부의 사용사례가 있나요? 정말 모루겠소요

2019-05-24 10:23 UTC, merged