Add Checkbox
daemabnb/Daema-BnB-web pull request #4
Opened 2019-05-21 05:06 UTC by khg0712

![image](https://user-images.githubusercontent.com/25566139/58069781-9b931600-7bd1-11e9-91b2-ee5f7df32911.png)

2019-05-21 11:58 UTC, engolder requested changes

2019-05-21 11:58 UTC, engolder commented on src/presentations/Checkbox/index.tsx
> +interface Props {
LabeledCheckbox로 바꿔주시고 export해주세요!

2019-05-21 11:58 UTC, engolder commented on src/presentations/Checkbox/index.tsx
> +  onChange: (event: React.ChangeEvent) => void;
컴포넌트 조상의 관점에서 보았을때 event객체보다는 value만 넣어주는 편이 좋아보입니다

2019-05-21 11:58 UTC, engolder commented on src/presentations/Checkbox/styles.ts
> +  type: 'checkbox',
이런 좋은 기능이있었다니.. 왜 말씀안해주셨습니까

2019-05-27 06:44 UTC, khg0712 commented on src/presentations/Checkbox/index.tsx
> +interface Props {
넵

2019-05-27 06:44 UTC, khg0712 commented on src/presentations/Checkbox/index.tsx
> +interface Props {
export는 하지 않을게요

2019-05-27 06:51 UTC, khg0712 commented on src/presentations/Checkbox/index.tsx
> +  onChange: (event: React.ChangeEvent) => void;
넵

2019-05-28 00:12 UTC, engolder commented on src/presentations/LabeledCheckbox/index.tsx
> +  const toggleCheckboxChange = onChange.bind(null, !isChecked);
handle prefix를 붙여주는것으로 통일하는건 어떨까요

2019-05-28 00:12 UTC, engolder commented on src/presentations/LabeledCheckbox/index.tsx
> +  const toggleCheckboxChange = onChange.bind(null, !isChecked);
bind메서드는 기존 method를 감싸는 **새로운**함수를 만드는 것으로 알고있습니다.
react hooks나 class를 사용하는 것이 좋겠네요!!

2019-05-28 00:25 UTC, engolder approved these changes

2019-05-28 06:35 UTC, merged