Date presenter
daemabnb/Daema-BnB-web pull request #6
Opened 2019-05-21 10:31 UTC by khg0712

2019-05-21 11:55 UTC, engolder requested changes

2019-05-21 11:55 UTC, engolder commented on src/presentations/DatePresenter/index.tsx
> +import { formatDate } from '../../utils/formatDate';
utils도 index.ts를 만들어서 import하는 편이 좋아보입니다

2019-05-21 11:55 UTC, engolder commented on src/presentations/DatePresenter/index.tsx
> +interface Props {
DatePresenterProps로 바꿔주세요. 그리고 export 해주세요!!

2019-05-21 11:55 UTC, engolder commented on src/presentations/DatePresenter/styles.ts
> +  font-size: 16px;
두 개의 요소를 사용하신 이유가있나요? DatePresenter하나만으로 충분해보입니다

2019-05-24 02:57 UTC, khg0712 commented on src/presentations/DatePresenter/index.tsx
> +interface Props {
이름은 바꿨지만 export할 필요가 있을까요?

2019-05-27 05:18 UTC, merged