List item
daemabnb/Daema-BnB-web pull request #8
Opened 2019-05-24 02:56 UTC by khg0712

2019-05-26 13:35 UTC, engolder requested changes

2019-05-26 13:35 UTC, engolder commented on src/presentations/ListItem/index.tsx
> +  itemId: string;
id가 string?

2019-05-26 13:35 UTC, engolder commented on src/presentations/ListItem/index.tsx
> +import { formatDate } from '../../utils';
index.ts

2019-05-26 13:35 UTC, engolder commented on src/presentations/ListItem/index.tsx
> +  returnDate: Date;
naming통일하는게 좋을 것 같네요 `returnedDate`이런식으로

2019-05-26 13:35 UTC, engolder commented on src/presentations/ListItem/index.tsx
> +  onClick?: () => void;
`onClick?(): void;`
형태로 할 수도 있습니다 참고하시라구~~

2019-05-26 13:35 UTC, engolder commented on src/presentations/ListItem/index.tsx
> +        </S.ListItemDateDescription>
제가 생각하기에 `ListItemDescriptionLeft`는 단순히 스타일을 위한 엘리먼트라서 마크업에서 핵심 역할이 아닌 것 같습니다.
저는 스타일을 위한 마크업을 지양하기때문에 만약 저였다면 아래처럼 했을것 같아요
```jsx
<S.ListItemName>{itemName}</S.ListItemName>
<S.ListItemOwner>{ownerName}</S.ListItemOwner>
<S.ListItemDateDescription>
  {`${formatDate(sharedDate)} ~ ${formatDate(returnDate)}`}
</S.ListItemDateDescription>
```

2019-05-26 13:35 UTC, engolder commented on src/presentations/ListItem/index.tsx
> +        </S.ListItemDateDescription>
template literal사용할 필요 없어요

2019-05-27 05:07 UTC, khg0712 commented on src/presentations/ListItem/index.tsx
> +  itemId: string;
예스

2019-05-27 05:08 UTC, khg0712 commented on src/presentations/ListItem/index.tsx
> +import { formatDate } from '../../utils';
가져와욧!

2019-05-27 05:08 UTC, khg0712 commented on src/presentations/ListItem/index.tsx
> +  returnDate: Date;
인종합니당!

2019-05-27 05:19 UTC, khg0712 commented on src/presentations/ListItem/index.tsx
> +  onClick?: () => void;
`onClick?: () => void;` 이게 더 예뻐보이는 것 같아요

2019-05-27 05:20 UTC, khg0712 commented on src/presentations/ListItem/index.tsx
> +        </S.ListItemDateDescription>
마자용!

2019-05-27 07:17 UTC, engolder approved these changes

2019-05-27 07:18 UTC, merged